In [1]:
! pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np
from sklearn.datasets import fetch_20newsgroups
from sklearn.model_selection import train_test_split
#from sklearn.feature_extraction.text import Tokenizer from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, Flatten
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [3]:
categories = ['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware',
              'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles',
              'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space',
              'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc',
              'talk.religion.misc']

newsgroup = fetch_20newsgroups(subset='all',categories=categories,shuffle=True, random_state=42)

In [4]:
x_train, x_test, y_train, y_test = train_test_split(newsgroup.data, newsgroup.target, test_size=0.2,random_state=42)

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
vectorizer = TfidfVectorizer(stop_words = 'english', max_features=500)
x_train_tfidf =  vectorizer.fit_transform(x_train)
x_test_tfidf = vectorizer.fit_transform(x_test)

In [7]:
from sklearn.naive_bayes import MultinomialNB

In [8]:
classifier = MultinomialNB()

In [9]:
classifier.fit(x_train_tfidf, y_train)

MultinomialNB()

In [10]:
y_pred = classifier.predict(x_test_tfidf)

In [11]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [12]:
acc = accuracy_score(y_test, y_pred)
print('Accuracy : ', acc)

Accuracy :  0.09283819628647215


In [13]:
acc = accuracy_score(y_test, y_pred)
accuracy1 = acc*100
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test,y_pred,target_names = newsgroup.target_names)

In [14]:
print(f"Accuracy: {accuracy1:.4f}")
print("\nConfusion Matriox:")
print(conf_matrix)
print("\nClassification report:")
print(classification_rep)

Accuracy: 9.2838

Confusion Matriox:
[[ 5 13  8  3  0  1  0  8  3  1  2  4 18 14 19  8 19 18  3  4]
 [ 4 15 20 11  3 13  7  6  2  6 13 16 19 11  9  4 21 16  6  0]
 [ 2  9 18 15  0 15  8  4 12  6  6 25 20  8  8  9 17  7  5  1]
 [ 3 14 14 19  4  8  9  4  6  2  7 23 10  2 10  5 24 11  6  2]
 [ 3 11 20 19  6  7  9 13  4  8  7 12 24 13  6  4 17 11  8  3]
 [ 2  9 33 25  4 49  7  2  3  7  5 10 10 12  7  0 11 14  4  1]
 [13  2  3  6  2  4 13 13  3 12  7 12 18 14 11 11 29 10  9  1]
 [ 4 12 11  7  2  0  3 13  1  6  6 10 24 42 16  6 20  7  3  3]
 [ 0  9  9  5  2  4  7  4  8  3  2 11 21 15 11  7 23 13  9  5]
 [10  5  9  9  3 12 11  9 13  3  6 12 17 15 11 10 36  9  8  3]
 [ 4  3  9  6  6 12 10 10 14  4 10 10 17  6 15 12 25 14  8  3]
 [ 8  7  6  2  2  6  6  6  6  2  4 25 18 16  8 27 16 13 19  4]
 [ 4 10  9 16  6  7  4  8  4 11  8  3 16 24  9 12 23 12  9  7]
 [ 4 14 11  8  4  5  2  6  6  8  3 13 24 22  5  7 28 13  7  4]
 [ 3  8  2  1  4  7  4 16  1  4  3 11 11 18 53  8 15 12  7  1]
 [ 6  7  4  5  4  

In [15]:
text = ['God Bless You!', 'Motor cycle is a bike.']
text_tfidf = vectorizer.transform(text)
predict_category = classifier.predict(text_tfidf)

In [16]:
print(f"predicted Category : {newsgroup.target_names[predict_category[1]]}")

predicted Category : rec.motorcycles
